version: "3.9"

services:
  fhir-server:
    image: alphora/cqf-ruler:0.14.2-SNAPSHOT
    #image: costateixeira/hapi:test
    #image: hapiproject/hapi:latest
    restart: always
    container_name: ${server_name}
    ports:
      - ${server_port:-8080}:8080
    environment:
       - hapi.fhir.allow_multiple_delete=true
       - hapi.fhir.reuse_cached_search_results_millis=1000

  busybox:
    image: costateixeira/busybox:latest
    volumes:
      - ./app:/home/static
    ports:
      - ${static_server_port:-8087}:3000